### ISSUE TITLE
Still under dev?

### ISSUE THREAD

**Issue by GetContented** [hailstorm-hs/hailstorm#2]
Quite interested in this - in particular, the Hint part discussed in your paper at the end.

Are you still developing this?

**Comment by turtlesoupy** [comment]
Hey @GetContented -- this was a research project that isn't under active development. I'm happy to answer any questions if you have some concerns. I've been meaning to update it so that it works for the latest haskakafka version but haven't gotten around to it yet.

**Comment by GetContented** [comment]
ah that's a pity... though I'm actually after something a bit more abstract anyway (less tied to Kafka and Zookeeper). Thanks for the response.
